import { Notification } from "@/src/interface/umkm";

export const dummyNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "order",
    title: "Pesanan Baru! 🎉",
    message:
      "Budi Santoso telah membeli 5 unit Dodol Kacang Bogor dengan total Rp 225.000. Status: Diproses",
    orderId: "1",
    orderNumber: "ORD-2026-001",
    customer: "Budi Santoso",
    product: "Dodol Kacang Bogor",
    status: "diproses",
    fromRole: "customer",
    createdAt: "2026-03-19T10:30:00",
    isRead: false,
  },
  {
    id: "notif-2",
    type: "status_update",
    title: "Pesanan Siap Dikirim ✓",
    message:
      "Pesanan ORD-2026-001 untuk Budi Santoso sudah siap dikirim. Driver akan segera mengambil barang.",
    orderId: "1",
    orderNumber: "ORD-2026-001",
    customer: "Budi Santoso",
    product: "Dodol Kacang Bogor",
    status: "dikirim",
    fromRole: "umkm",
    createdAt: "2026-03-18T14:20:00",
    isRead: true,
  },
  {
    id: "notif-3",
    type: "delivery",
    title: "Pesanan dalam Pengiriman 🚚",
    message:
      "Pesanan ORD-2026-001 sedang dalam pengiriman. Driver akan tiba dalam waktu 2-3 jam.",
    orderId: "1",
    orderNumber: "ORD-2026-001",
    customer: "Budi Santoso",
    product: "Dodol Kacang Bogor",
    status: "dikirim",
    fromRole: "driver",
    createdAt: "2026-03-18T15:45:00",
    isRead: true,
  },
  {
    id: "notif-4",
    type: "order",
    title: "Pesanan Baru! 🎉",
    message:
      "Siti Nurhaliza telah membeli 10 unit Teh Herbal Bogor dengan total Rp 300.000. Status: Diproses",
    orderId: "2",
    orderNumber: "ORD-2026-002",
    customer: "Siti Nurhaliza",
    product: "Teh Herbal Bogor",
    status: "diproses",
    fromRole: "customer",
    createdAt: "2026-03-18T09:15:00",
    isRead: true,
  },
  {
    id: "notif-5",
    type: "status_update",
    title: "Pesanan Selesai! 🎊",
    message:
      "Pesanan ORD-2026-002 untuk Siti Nurhaliza telah sampai tujuan dan selesai diterima.",
    orderId: "2",
    orderNumber: "ORD-2026-002",
    customer: "Siti Nurhaliza",
    product: "Teh Herbal Bogor",
    status: "selesai",
    fromRole: "customer",
    createdAt: "2026-03-18T17:30:00",
    isRead: true,
  },
];
